name: Extract Branch Issue Number

on:
    workflow_call:
        inputs:
            branch_name:
                required: true
                type: string
        outputs:
            issue_number:
                description: "The extracted issue number from the branch name"
                value: ${{ jobs.extract.outputs.issue_number }}

jobs:
    extract:
        runs-on: ubuntu-latest
        outputs:
            issue_number: ${{ steps.extract.outputs.issue_number }}
        steps:
            - name: Extract Issue Number from Branch Name
              id: extract
              run: |
                  BRANCH_NAME="${{ inputs.branch_name }}"
                  if [[ "$BRANCH_NAME" =~ ^[^/]+/#([0-9]+)-.*$ ]]; then
                    ISSUE_NUMBER="${BASH_REMATCH[1]}"
                    echo "Valid branch name. Extracted issue number: $ISSUE_NUMBER"
                    echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
                  else
                    echo "Branch name does not match the expected format ([any string]/#[number]-[any string])."
                    exit 1
                  fi
