name: Redirect PR Target Branch

on:
    pull_request_target:
        types: [opened]
    workflow_call: {}

jobs:
    redirect_pr:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - name: Check and Update Base Branch
              if: github.base_ref == 'main' && (github.head_ref != 'dev' && github.head_ref != 'develop' && github.head_ref != 'staging')
              run: |
                  PR_NUMBER=${{ github.event.pull_request.number }}
                  REPO=${{ github.repository }}

                  # Update the PR base branch to dev
                  curl -X PATCH \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
                    -d '{"base":"dev"}'

                  # Add a comment to explain the change
                  curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments" \
                    -d '{"body":"⚠️ This PR was automatically redirected to target the `dev` branch instead of `main`. All PRs should go through `dev` first."}'

    trigger_zenhub_workflow:
        needs: redirect_pr
        uses: ./.github/workflows/zenhub-move-review.yml
        secrets: inherit
